# Generated by Django 5.1.4 on 2025-01-25 21:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='messageencrypted',
            old_name='sequence_number',
            new_name='salt',
        ),
    ]
